# Generated by Django 6.0.1 on 2026-01-07 07:07

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True, default='Welcome to my New Archery Scoring website'),
        ),
    ]
