# Generated by Django 6.0.1 on 2026-01-27 15:46

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoringpage',
            name='scoring',
            field=wagtail.fields.StreamField([], block_lookup={}),
        ),
    ]
