# Generated by Django 6.0.1 on 2026-01-10 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='archers',
            field=models.ManyToManyField(blank=True, help_text='format: not required', related_name='category_archers', through='scoring.CategoryMembership', to='scoring.archer', verbose_name='Archers'),
        ),
        migrations.AlterField(
            model_name='categorymembership',
            name='author',
            field=models.ForeignKey(default=1, help_text='format: required, default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='categorymembership_author', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='categorymembership',
            name='category',
            field=models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.PROTECT, related_name='categorymembership_category', to='scoring.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='author',
            field=models.ForeignKey(default=1, help_text='format: not required, default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='competition_author', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='rounds',
            field=models.ManyToManyField(blank=True, help_text='format: not required', related_name='competition_rounds', through='scoring.CompetitionMembership', to='scoring.round', verbose_name='Competition rounds'),
        ),
        migrations.AlterField(
            model_name='competitionmembership',
            name='author',
            field=models.ForeignKey(default=1, help_text='format: required, default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='competitionmembership_author', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='round',
            name='author',
            field=models.ForeignKey(default=1, help_text='format: not required, default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='round_author', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='roundmembership',
            name='archer',
            field=models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.PROTECT, related_name='roundmembership_archer', to='scoring.archer', verbose_name='Archer'),
        ),
        migrations.AlterField(
            model_name='roundmembership',
            name='author',
            field=models.ForeignKey(default=1, help_text='format: required, default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='roundmembership_author', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='roundmembership',
            name='round',
            field=models.ForeignKey(default=1, help_text='format: required', on_delete=django.db.models.deletion.PROTECT, related_name='roundmembership_round', to='scoring.round', verbose_name='Round'),
        ),
        migrations.AlterField(
            model_name='targetfacenamechoice',
            name='author',
            field=models.ForeignKey(default=1, help_text='format: required, default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='targetfacenamechoice_author', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='team',
            name='archers',
            field=models.ManyToManyField(blank=True, help_text='format: not required', related_name='team_archers', through='scoring.TeamMembership', to='scoring.archer', verbose_name='Archers'),
        ),
        migrations.AlterField(
            model_name='teammembership',
            name='author',
            field=models.ForeignKey(default=1, help_text='format: required, default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='teammembership_author', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
    ]
