# Generated by Django 6.0.1 on 2026-01-22 06:20

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archerpagemembers',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='archer_page_members', to='scoring.archerpage'),
        ),
    ]
