# Generated by Django 6.0.1 on 2026-01-11 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0002_alter_category_archers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymembership',
            name='archer',
            field=models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.PROTECT, related_name='categorymembership_archer_items', to='scoring.archer', verbose_name='Archer'),
        ),
        migrations.AlterField(
            model_name='categorymembership',
            name='category',
            field=models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.PROTECT, related_name='categorymembership_category_items', to='scoring.category', verbose_name='Category'),
        ),
    ]
