# Generated by Django 6.0.1 on 2026-01-22 07:25

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0002_alter_archerpagemembers_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='archerpage',
            name='archers',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='scoring.archer'),
        ),
        migrations.AlterField(
            model_name='archerpagemembers',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='archer_members', to='scoring.archerpage'),
        ),
    ]
