# Generated by Django 6.0.1 on 2026-01-29 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0003_archerpagemembers_authors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archerpagemembers',
            name='authors',
        ),
    ]
