# Generated by Django 6.0.1 on 2026-01-22 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0003_archerpage_archers_alter_archerpagemembers_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archerpage',
            name='archers',
        ),
    ]
