# Generated by Django 6.0.1 on 2026-01-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0003_alter_categorymembership_archer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='archers',
            field=models.ManyToManyField(blank=True, help_text='format: not required', related_name='discipline_archers', through='scoring.DisciplineMembership', to='scoring.archer', verbose_name='Archers'),
        ),
    ]
