# Generated by Django 6.0.1 on 2026-01-30 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0003_disciplinepage_image'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmembershippage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='ClubMembershipPage image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='clubpage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='ClubPage image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='disciplinemembershippage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='DisciplineMembershipPage image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
