# Generated by Django 6.0.1 on 2026-01-15 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0004_alter_discipline_archers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetfacenamechoice',
            name='name',
            field=models.CharField(help_text='format: required, max-128', max_length=128, unique=True, verbose_name='Name'),
        ),
    ]
