# Generated by Django 6.0.1 on 2026-01-30 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0004_clubmembershippage_image_clubpage_image_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorypage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='CategoryPage image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
