# Generated by Django 6.0.1 on 2026-01-30 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0005_categorypage_image'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='agegrouppage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='AgeGroupPage image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='categorymembershippage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='ArcherPage image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='teampage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='TeamPage image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
