# Generated by Django 6.0.1 on 2026-01-29 12:28

import modelcluster.fields
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0005_disciplinemembershippage_authors_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='categorypage',
            name='authors',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clubmembershippage',
            name='authors',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clubpage',
            name='authors',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
