# Generated by Django 6.0.1 on 2026-01-23 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0005_archer_expire_at_archer_expired_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archer',
            name='expire_at',
        ),
        migrations.RemoveField(
            model_name='archer',
            name='expired',
        ),
        migrations.RemoveField(
            model_name='archer',
            name='first_published_at',
        ),
        migrations.RemoveField(
            model_name='archer',
            name='go_live_at',
        ),
        migrations.RemoveField(
            model_name='archer',
            name='has_unpublished_changes',
        ),
        migrations.RemoveField(
            model_name='archer',
            name='last_published_at',
        ),
        migrations.RemoveField(
            model_name='archer',
            name='latest_revision',
        ),
        migrations.RemoveField(
            model_name='archer',
            name='live',
        ),
        migrations.RemoveField(
            model_name='archer',
            name='live_revision',
        ),
        migrations.RemoveField(
            model_name='archer',
            name='locked',
        ),
        migrations.RemoveField(
            model_name='archer',
            name='locked_at',
        ),
        migrations.RemoveField(
            model_name='archer',
            name='locked_by',
        ),
    ]
