# Generated by Django 6.0.1 on 2026-01-30 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0006_agegrouppage_image_categorymembershippage_image_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionmembershippage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='CompetitionMembershipPage image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='competitionpage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='CompetitionPage image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='roundmembershippage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='RoundMembershipPage image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='roundpage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='RoundPage image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='scorepage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='ScorePage image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='scoringpage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='ScoringPage image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='scoringsheetpage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='ScoringSheetPage image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='targetfacenamechoicepage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='TargetFaceNameChoicePage image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='targetfacepage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='TargetFacePage image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='teammembershippage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='TeamMembershipPage image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
