# Generated by Django 6.0.1 on 2026-01-27 07:40

import django.db.models.deletion
import django.utils.timezone
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0006_remove_archer_expire_at_remove_archer_expired_and_more'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseGridPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('subtitle', models.CharField(blank=True, max_length=100)),
                ('body', wagtail.fields.RichTextField(blank=True)),
                ('grid', wagtail.fields.StreamField([('table', 0)], block_lookup={0: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'table_options': {'colHeaders': True, 'editor': 'text', 'minSpareRows': 0, 'rowHeaders': False, 'startCols': 3, 'startRows': 3, 'stretchH': 'all'}})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
