# Generated by Django 6.0.1 on 2026-01-29 14:48

import modelcluster.fields
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0007_agegrouppage_authors'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agegrouppagemembers',
            name='authors',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='categorymembershippage',
            name='authors',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teammembershippage',
            name='authors',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teampage',
            name='authors',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
