# Generated by Django 6.0.1 on 2026-01-27 11:53

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0007_basegridpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basegridpage',
            name='grid',
            field=wagtail.fields.StreamField([('table', 0)], block_lookup={0: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'table_options': {'colHeaders': True, 'contextMenu': ['row_above', 'row_below', '---------', 'col_left', 'col_right', '---------', 'remove_row', 'remove_col', '---------', 'undo', 'redo', '---------', 'copy', 'cut', '---------', 'alignment'], 'editor': 'text', 'height': 108, 'minSpareRows': 3, 'rowHeaders': False, 'startCols': 3, 'startRows': 3, 'stretchH': 'none'}})}),
        ),
    ]
