# Generated by Django 6.0.1 on 2026-01-29 14:59

import modelcluster.fields
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0008_agegrouppagemembers_authors_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='roundmembershippage',
            name='authors',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roundpage',
            name='authors',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scoringsheetpage',
            name='authors',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='targetfacenamechoicepage',
            name='authors',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='targetfacepage',
            name='authors',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
