# Generated by Django 6.0.1 on 2026-01-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_grid_model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplegrid',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
