# Generated by Django 6.0.1 on 2026-01-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_grid_model', '0002_alter_simplegrid_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplegrid',
            name='data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
